---
- name: change e-mail address for web-server
  hosts: web_servers
  become: true
  tasks: 
    - name: change e-mail address for admin
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: ServerAdmin somebody@somewhere.net
      when: ansible_distribution == "CentOS"
      register: httpd

    - name: restart httpd
      systemd:
        name: httpd
        state: restarted
      when: httpd.changed
