---

- hosts: all
  become: true
  tasks:

  - name: stop httpd
    tags: stop
    systemd:
      name: httpd
      state: stopped

  - name: remove httpd
    tags: remove
    yum:
      name: httpd
      state: absent

